server/modules/layout_state_machine.js
=> Refact: server/modules/layout_state_machine.js to es6

server/modules/client_control_state_machine.js
=> Refact: server/modules/client_control_state_machine.js to es6

client/client.js
=> Refact: client/client.js to es6

client/title_card.js
=> Refact: client/title_card.js to es6

client/demo.js
=> Refact: client/demo.js to es6

client/fake_require.js
=> Refact: client/fake_require.js to es6

client/modules/client_state_machine.js
=> Refact: client/modules/client_state_machine.js to es6

client/modules/module_manager.js
=> Refact: client/modules/module_manager.js to es6

client/modules/module_ticker.js
=> Refact: client/modules/module_ticker.js to es6

client/network/network.js
=> Refact: client/network/network.js to es6

client/network/neighbor_persistence.js
=> Refact: client/network/neighbor_persistence.js to es6

client/modules/module.js
=> Refact: client/modules/module.js to es6

client/status/status.js
=> Refact: client/status/status.js to es6

server/modules/playlist_driver.js
=> Refact: server/modules/playlist_driver.js to es6

server/modules/module_ticker.js
=> Refact: server/modules/module_ticker.js to es6

server/modules/playlist_loader.js
=> Refact: server/modules/playlist_loader.js to es6

server/modules/server_state_machine.js
=> Refact: server/modules/server_state_machine.js to es6

server/modules/module_state_machine.js
=> Refact: server/modules/module_state_machine.js to es6

server/modules/module_loader.js
=> Refact: server/modules/module_loarder.js to es6

server/modules/module_library.js
=> Refact: server/modules/module_library.js to es6

server/modules/module_def.js
=> Refact: server/modules/module_def.js to es6

server/network/network.js
=> Refact: server/network/network.js to es6

server/util/credentials.js
=> Refact: server/util/credentials.js to es6

server/util/googleapis.js
=> Refact: server/util/googleapis.js to es6

server/util/time.js
=> Refact: server/util/time.js to es6

server/util/wall_geometry.js
=> Refact: server/util/wall_geometry to es6

server/fake_require.js
=> Refact: server/fake_require.js to es6

server/control.js
=> Refact: server/control.js to es6

server/webapp.js
=> Refact: server/webapp.js to es6

server/server.js
=> Refact: server/server.js to es6

server/game/game.js
=> Refact: server/game.js to es6

client/monitoring/monitor.js
=> Refact: client/monitoring/monitor.js to es6

server/.jshintrc
Don't merge now, maybe we should create a special issue before
=> Refact: Update the jshintrc of server folder

client/surface/p5_surface.js
=> Refact: client/surface/p5_surface.js to es6

client/util/time.js
=> Refact: client/util/time.js to ES6

client/util/info.js
=> Refact: client/util/info.js to ES6

client/util/load_youtube_api.js
=> Refact: client/util/load_youtube_api.js to ES6

client/util/location.js
=> Refact: client/util/location.js to ES6

client/util/log.js
=> Refact: client/util/log.js to ES6

client/util/message.js
=> Refact: client/util/message.js to ES6

client/state/state_manager.js
=> Refact: client/state/state_manager.js to es6

client/asset/asset.js
Converted client/asset.js. Made use of arrow functions.
=> Refact: client/asset/asset.js to es6

client/surface/canvas_surface.js
=> Refact: client/surface/canvas_surface.js to es6

server/state/state_schedule.js
=> Refact: server/state/state_schedule.js to es6

server/state/state_manager.js
=> Refact: server/state/state_manager.js to es6

server/util/log.js
=> Refact: server/util/log.js to es6

server/monitoring/monitor.js
=> Refact server/monitor.js to es6

client/surface/surface.js
=> Refact: client/surface/surface.js to es6

client/surface/threejs_surface.js
=> Refact: client/surface/threejs_surface.js to es6

client/util/debug.js
=>  Refact: client/util/debug.js to ES6, changed styling according to Google Style Guide

client/surface/p5_surface.js
=> Fix:p5_surface made into class
